[session]
initial_positions = [[0.5, 0.0, 0.0], [0.0, 5.0, 0.0]]
leader_trajectory = "./data/straight_trajectory_data.npz"
save_name = "./data/straight_optimization_results_o2_log_v2.npz"
video_name = "./data/media/straight_optimization_results.mp4"

[model]
n_robots = 2
robot_mass = 1.0
interrobot_observation_kind = "distance"

[stlog]
order = 1
dt = 0.2

[opc]
window_size = 5
observed_components = []
max_inter_vehicle_distance = 4
min_inter_vehicle_distance = 0.2

[optim]
method = "trust-constr"
ub = [1.0, 0.0, 4.0, 2.0]
lb = [1.0, 0.0, 0.0, -2.0]

[optim.options]
xtol = 1e-4
gtol = 1e-8
disp = false
verbose = 0
maxiter = 100

[sim]
steps = 500
