n_robots = 2

[session]

save_name = "/home/hs293go/Dropbox/datasets/test_trajectory_v0.npz"
video_name = "/home/hs293go/Dropbox/datasets/straight_optimization_results.mp4"

[leader.trajectory]
waypoints = [
    [0.0, 0.0, 10.0],  #
    [10.0, 0.0, 10.0],

]
timestamps = [0, 120]
timestep = 0.05
model_mass = 1.0

[followers]
init_state = [[0.0, 2.0, 7.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]]


[stlog]
order = 1
dt = 0.2

[opc]
window_size = 15
observed_components = [10, 11, 12]
max_inter_vehicle_distance = 3.5
min_inter_vehicle_distance = 1.0

[optim]
method = "trust-constr"
ub = [12.0, 1.0, 1.0, 2.0]
lb = [0.0, -1.0, -1.0, -2.0]


[optim.options]
xtol = 1e-3
gtol = 1e-4
disp = false
verbose = 0
maxiter = 100


[sim]
steps = 4000
