n_robots = 2

[session]

save_name = "~/.cache/observability_aware_control/data/optimization_results_stlog.npz"
video_name = "~/.cache/observability_aware_control/data/straight_optimization_results.mp4"

[leader.trajectory]
waypoints = [
  [0.0, 0.0, 10.0],  #
  [10.0, 0.0, 10.0],

]
timestamps = [0, 120]
timestep = 0.05
model_mass = 1.0

[followers]
init_state = [[0.0, 2.0, 7.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0]]


[stlog]
order = 5
dt = 0.2

[opc]
window_size = 20
observed_components = [0, 1, 2, 7, 8, 9]
max_inter_vehicle_distance = 3.0
min_inter_vehicle_distance = 1.0

[optim]
method = "trust-constr"
ub = [30.0, 4.0, 4.0, 6.0]
lb = [0.0, -4.0, -4.0, -6.0]


[optim.options]
disp = false
verbose = 0
maxiter = 40

[sim]
steps = 4000
